route:
  receiver: email-me
receivers:
- name: email-me
  email_configs:
  - to: ny40ny40ny@gmail.com
    from: ny40ny40ny@gmail.com
    smarthost: smtp.gmail.com:587
    auth_username: ny40ny40ny@gmail.com
    auth_identity: ny40ny40ny@gmail.com
    auth_password: pnwjvowhzpsnqkqs
